"""
Aggregate per-series metrics from every tier into a single leaderboard.

Reads <SSD>/tier{0,1,2}_*/output/metrics_<target>.csv (per-series × fold ×
horizon × model), aggregates cross-fold + cross-series mean & median, and emits:
  scoreboard.html     interactive, sortable, self-contained (committable)
  _leaderboard.md      markdown tables for the README
Usage:  ./run.sh build_scoreboard.py
"""
from __future__ import annotations

import os
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent
SSD = Path(os.environ.get('EQUITY_FORECAST_HOME', '/mnt/ssd/equity_forecast'))
TIERS = {
    'tier0': SSD / 'tier0_baselines' / 'output',
    'tier1': SSD / 'tier1_classical' / 'output',
    'tier2': SSD / 'tier2_global_ml' / 'output',
}
TARGETS = ['close', 'log_return']
HORIZONS = [5, 20, 60]
META = {'unique_id', 'metric', 'horizon', 'fold', 'test_end'}
ASSET_DIR = ROOT / 'assets' / 'forecasts'


def load_long() -> pd.DataFrame:
    frames = []
    for tier, d in TIERS.items():
        for target in TARGETS:
            fp = d / f'metrics_{target}.csv'
            if not fp.exists():
                continue
            df = pd.read_csv(fp)
            df = df[df['fold'].astype(str) != 'single']        # CV folds only
            model_cols = [c for c in df.columns if c not in META]
            long = df.melt(id_vars=['unique_id', 'metric', 'horizon', 'fold'],
                           value_vars=model_cols, var_name='model', value_name='value')
            long['tier'] = tier
            long['target'] = target
            long['label'] = tier + ':' + long['model']
            frames.append(long)
    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True)


def board(long: pd.DataFrame, target: str, horizon: int) -> pd.DataFrame:
    sub = long[(long['target'] == target) & (long['horizon'] == horizon)]
    if sub.empty:
        return pd.DataFrame()
    sub = sub.dropna(subset=['value'])
    g = sub.groupby(['label', 'metric'])['value']
    mean = g.mean().unstack('metric')
    med = sub[sub['metric'] == 'mase'].groupby('label')['value'].median()
    out = pd.DataFrame(index=mean.index)
    out['MASE'] = mean.get('mase')
    out['MASE_med'] = med
    out['MAE'] = mean.get('mae')
    out['RMSE'] = mean.get('rmse')
    out['sMAPE'] = mean.get('smape')
    out = out.sort_values('MASE').reset_index().rename(columns={'label': 'model'})
    out.insert(0, 'rank', range(1, len(out) + 1))
    return out


def fmt(df: pd.DataFrame) -> pd.DataFrame:
    d = df.copy()
    for c in ('MASE', 'MASE_med'):
        d[c] = d[c].map(lambda v: f'{v:.3f}' if pd.notna(v) else '—')
    for c in ('MAE', 'RMSE'):
        d[c] = d[c].map(lambda v: f'{v:.4g}' if pd.notna(v) else '—')
    d['sMAPE'] = d['sMAPE'].map(lambda v: f'{v:.4g}' if pd.notna(v) else '—')
    return d


def to_md(long: pd.DataFrame) -> str:
    lines = ['<!-- generated by build_scoreboard.py -->']
    for target in TARGETS:
        lines.append(f'\n#### Target: `{target}`')
        for h in HORIZONS:
            b = board(long, target, h)
            if b.empty:
                continue
            lines.append(f'\n**Horizon {h} trading days** — ranked by MASE (lower is better)\n')
            d = fmt(b)
            lines.append('| Rank | Model | MASE | MASE (median) | MAE | RMSE | sMAPE |')
            lines.append('|---:|:--|--:|--:|--:|--:|--:|')
            for _, r in d.iterrows():
                lines.append(f"| {r['rank']} | `{r['model']}` | {r['MASE']} | "
                             f"{r['MASE_med']} | {r['MAE']} | {r['RMSE']} | {r['sMAPE']} |")
    return '\n'.join(lines) + '\n'


def gallery_html() -> str:
    if not ASSET_DIR.exists():
        return '<p>No forecast charts yet.</p>'
    imgs = sorted(ASSET_DIR.glob('*.png'))
    cells = ''.join(
        f'<figure><img src="assets/forecasts/{p.name}" loading="lazy">'
        f'<figcaption>{p.stem}</figcaption></figure>' for p in imgs)
    return f'<div class="gallery">{cells}</div>'


def to_html(long: pd.DataFrame) -> str:
    css = """
    body{font:14px/1.5 system-ui,sans-serif;margin:2rem;color:#1a1a1a;background:#fafafa}
    h1{margin-bottom:.2rem} h2{margin-top:2rem;border-bottom:2px solid #ddd}
    table{border-collapse:collapse;margin:.6rem 0 1.4rem;background:#fff;box-shadow:0 1px 3px #0001}
    th,td{padding:.4rem .7rem;border-bottom:1px solid #eee;text-align:right}
    th:nth-child(2),td:nth-child(2){text-align:left}
    th{cursor:pointer;background:#f3f3f3;position:sticky;top:0}
    tr:first-child td{font-weight:600}
    .best{background:#e7f6e7}
    .gallery{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:1rem}
    .gallery img{width:100%;border:1px solid #eee;border-radius:6px}
    figcaption{font-size:12px;color:#666;text-align:center}
    """
    js = """
    function sortTable(t,n){let r=[...t.tBodies[0].rows];let asc=t.dataset.asc!==n+'';
    r.sort((a,b)=>{let x=a.cells[n].innerText,y=b.cells[n].innerText;
    let nx=parseFloat(x),ny=parseFloat(y);if(!isNaN(nx)&&!isNaN(ny)){return asc?nx-ny:ny-nx;}
    return asc?x.localeCompare(y):y.localeCompare(x);});t.dataset.asc=asc?n:'';
    r.forEach(x=>t.tBodies[0].appendChild(x));}
    """
    parts = [f'<!doctype html><meta charset=utf-8><title>Nifty50 Forecast Scoreboard</title>',
             f'<style>{css}</style>',
             '<h1>Nifty50 Forecasting Scoreboard</h1>',
             '<p>Walk-forward CV (6 folds). Lower MASE is better; MASE&lt;1 beats the '
             'in-sample seasonal-naive. Click a header to sort.</p>']
    for target in TARGETS:
        parts.append(f'<h2>Target: {target}</h2>')
        for h in HORIZONS:
            b = board(long, target, h)
            if b.empty:
                continue
            d = fmt(b)
            parts.append(f'<h3>Horizon {h} trading days</h3>')
            head = ''.join(f'<th onclick="sortTable(this.closest(\'table\'),{i})">{c}</th>'
                           for i, c in enumerate(d.columns))
            body = ''
            for ri, (_, r) in enumerate(d.iterrows()):
                cls = ' class="best"' if ri == 0 else ''
                body += '<tr>' + ''.join(f'<td{cls}>{r[c]}</td>' for c in d.columns) + '</tr>'
            parts.append(f'<table data-asc=""><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>')
    parts.append('<h2>Live forward forecasts (next ~60 business days)</h2>')
    parts.append(gallery_html())
    parts.append(f'<script>{js}</script>')
    return '\n'.join(parts)


def main():
    long = load_long()
    if long.empty:
        print('no metrics found — run the tiers first'); return
    (ROOT / 'scoreboard.html').write_text(to_html(long))
    (ROOT / '_leaderboard.md').write_text(to_md(long))
    print(f'wrote {ROOT / "scoreboard.html"}')
    print(f'wrote {ROOT / "_leaderboard.md"}')
    # console headline
    for target in TARGETS:
        b = board(long, target, 20)
        if not b.empty:
            print(f'\n=== {target} @ h=20 (top 5 by MASE) ===')
            print(fmt(b).head(5).to_string(index=False))


if __name__ == '__main__':
    main()
